# Theme configuration
theme: jekyll-theme-cayman
title: QPTmaths
description: Soporte de deeplinks para las aplicaciones de QPTmaths

# Files/directories to include
include: 
  - ".well-known"
  - "google73bd32ef1e25e1a9"

# Plugins
plugins:
  - jekyll-redirect-from

# Collections
collections:
  es:
    output: true
    permalink: /es/:path/

# Default configurations
defaults:
  # Default redirect for most pages
  -
    scope:
      path: "" # This means all files in the project
    values:
      redirect_to: "https://serlou.github.io/"
  
  # Exception for .well-known directory
  -
    scope:
      path: ".well-known"
    values:
      redirect_to: "" # Empty string means no redirect
  
  # Exception for google verification file
  -
    scope:
      path: "google73bd32ef1e25e1a9"
    values:
      redirect_to: "" # Empty string means no redirect

  # Configuration for Spanish pages
  -
    scope:
      path: ""
      type: "es"
    values:
      layout: "empty"
      redirect_to: "" # No redirect for Spanish pages

# You can add any other configurations here, such as:
# google_analytics: Your GA Tracking ID
