# Theme configuration
theme: jekyll-theme-cayman
title: QPTmaths
description: Soporte de deeplinks para las aplicaciones de QPTmaths

# Files/directories to include
include: 
  - ".well-known"
  - "google73bd32ef1e25e1a9"

defaults:
  - scope:
      path: "es"
    values:
      layout: "sitemap"
  - scope:
      path: "en"
    values:
      layout: "sitemap"

# You can add any other configurations here, such as:
# google_analytics: Your GA Tracking ID
